### ISSUE TITLE
net_cls interfering with lxd on linux

### ISSUE THREAD

**Issue by derrickmehaffy** [pia-foss/desktop#50] opened 2022-12-17 06:01 UTC
**Describe the bug**
Much like the following bug from mullvadvpn: https://github.com/mullvad/mullvadvpn-app/issues/3651

With the PIA desktop app installed it's throwing issues when trying to start an lxc/lxd container (see this forum thread: https://discuss.linuxcontainers.org/t/help-help-help-cgroup2-related-issue-on-ubuntu-jammy-with-mullvad-and-privateinternetaccess-vpn/14705/14

**To Reproduce**
1. Install LXD on any Linux distro that can install snaps (`sudo snap install lxd`)
2. Ensure PIA Desktop App is installed and running
3. Initialize LXD: `sudo lxd init` (just take all defaults)
4. Try to launch a basic ubuntu container: `sudo lxc launch ubuntu:22.04 test`
5. Container will fail to launch, use the following command to see log: `sudo lxc info --show-log test`
6. See error

Note: if you close PIA VPN than lxc can properly launch containers, this absolutely is caused by PIA's Desktop application.

**Expected behavior**
Mount net_cls anywhere else lol or alternatively add an env var/setting that will allow mounting net_cls somewhere else on a per user basis such as what was done here: https://github.com/mullvad/mullvadvpn-app/pull/3660

**Observed on:**
 - OS: Linux Mint 21.1
 - OS Kernel: 5.15.0-56-generic
 - Version 3.3.1

**Comment by laiweihwa** [comment] 2023-01-06 20:22
Same here. The problem is that cgroup is mounted on top of cgroup2

```
null@Null:~$ grep cgroup /proc/mounts
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
none /sys/fs/cgroup/net_cls cgroup rw,relatime,net_cls 0 0
```

Temp fixes include disabling cgroup2 or unmounting net_cls `sudo umount /sys/fs/cgroup/net_cls `

**Comment by MatrixNorm** [comment] 2023-06-19 12:32
Possible walkaround: edit `/etc/systemd/system/piavpn.service` file and add ExecStartPost directive:

```
[Service]
Environment="LD_LIBRARY_PATH=/opt/piavpn/lib"
ExecStart=/opt/piavpn/bin/pia-daemon
ExecStartPost=umount -l /sys/fs/cgroup/net_cls:
Restart=always

```

**Comment by etamme** [comment] 2023-10-08 20:58
+1 if i stop pia and umount /sys/fs/cgroup/net_cls everything starts working

**Comment by kp-john-mair** [comment] 2023-12-14 06:40
This should be fixed now thanks for the report

**Closed by kp-john-mair** 2023-12-14 06:40 UTC
