### ISSUE TITLE
pia-daemon is too slow to stop

### ISSUE THREAD

**Issue by TheDcoder** [pia-foss/desktop#58] opened 2023-06-27 23:28 UTC
**Describe the bug**

The `pia-daemon` is taking up a lot of time to stop, on my system it takes more than 15 seconds:

```
# time systemctl stop piavpn

________________________________________________________
Executed in   16.69 secs      fish           external
   usr time    5.10 millis  908.00 micros    4.19 millis
   sys time    8.12 millis  454.00 micros    7.67 millis
```

This is very annoying if you have the service running before shutdown, as it hogs up the shutdown until it stops.

**To Reproduce**

Not sure if it happens to everyone, but it happens to me and I did not do anything special. I only enabled the systemd service.

**Expected behavior**

It stops sooner.

**Observed on:**
 - OS: Arch Linux
 - Version `piavpn-bin 3.3.1_06924-1` (from AUR)

**Comment by kp-john-mair** [comment] 2023-08-28 19:03
Hi, have you tried the beta ? (Settings -> help -> receive beta updates). Let me know if you still experience issues with that one!

**Comment by TheDcoder** [comment] 2023-08-31 16:28
@kp-john-mair I can't do that since I'm using Arch Linux and I doubt you have official support for it, also I'm not really the kind of person who uses the built-in updater, I prefer making my own packages.

So are the beta builds publicly downloadable?

**Comment by TheDcoder** [comment] 2023-08-31 16:40
I tested with the latest `3.4-beta.1-07585` build and it still takes up a lot of time to stop:

```
# time systemctl stop piavpn

________________________________________________________
Executed in    6.10 secs      fish           external
   usr time    8.97 millis  135.00 micros    8.84 millis
   sys time   12.47 millis  612.00 micros   11.86 millis
```

The ~10 seconds reduction is due to me testing on a different PC with a more powerful CPU.

**Comment by kp-john-mair** [comment] 2023-09-02 18:02
I can reproduce it, thanks, I’ll add a ticket for it and hopefully we’ll look into it soon!

**Comment by TheDcoder** [comment] 2023-09-02 18:07
You don't develop in GitHub?

**Comment by kp-john-mair** [comment] 2023-09-02 18:14
@TheDcoder we use jira as our ticketing system rather than github issues ☺️

**Comment by kp-john-mair** [comment] 2023-10-17 12:51
Hi, we identified the issue as caused by `iptables` - it's very slow to remove some of our filters. Interestingly it's only slow on some distros, not others. There's not much we can do about it other than rewrite the firewall rules to use `nftables` instead (assuming nftables doesn't also have this issue). Closing for now! but thanks for the feedback!

**Closed by kp-john-mair** 2023-10-17 12:51 UTC
