### ISSUE TITLE
"Auto" mode for menu bar item not working

### ISSUE THREAD

**Issue by SebastianRasch** [pia-foss/desktop#26] opened 2021-04-09 11:47 UTC
**Describe the bug**
When setting the option "Icon style in menu bar" to "Auto", the menu bar icon is always dark, no matter if the other menu bar items are dark or white.

**To Reproduce**
1. Go to 'settings' > 'General'
2. Click on 'Icon style in menu bar' (not sure about the English text, in German it is "Symbolstil im Infobereich")
3. Choose 'Auto'
4. The menu bar icon is now always dark, even if all other menu bar items are white

**Expected behavior**
The menu bar icon should automatically change the appearance according to the background image, e.g. when the macOS system menu bar items are in light mode, the PIA icon should be white, too, and only when the system menu bar items are in dark mode, the PIA icon should be dark.

This is a new feature on macOS 11 Big Sur where the icon appearance changes depending on the background image (menu bar set to transparent). I use several spaces with different background images, so on some spaces, the icons are white, and on some the icons are black. They change in realtime upon switching spaces. Except the PIA icon, which always remains dark.

**Observed on:**
 - OS: macOS 11
 - Version 11.2.3

![Bildschirmfoto 2021-04-09 um 13 41 16](https://user-images.githubusercontent.com/22617697/114176888-096a9700-993c-11eb-8c86-b0351521f066.png)

![Bildschirmfoto 2021-04-09 um 13 37 22](https://user-images.githubusercontent.com/22617697/114177205-69613d80-993c-11eb-88ab-7b4ecb68f966.png)

**Comment by JonathonH-PIA** [comment] 2021-04-10 15:28
Thanks for the detailed report @SebastianRasch , this is a duplicate of #5 so I've commented on this issue there.

**Comment by SebastianRasch** [comment] 2021-04-11 15:45
No this has nothing to do with the system dark/light mode at all. It has to do with the dynamic presentation of menu bar items based on the background (wallpaper). That's a different problem entirely.
On Big Sur, menu bar items can be both dark or light, depending on the wallpaper, no matter if the system is set to dark or light. So for example when the system is in dark mode, menu items still can be dark, too. Previously, menu items would only be white when the system is in dark mode but this has changed in macOS 11.

This is not a feature request, it's a bug since the menu bar on macOS 11 is completely different to the one in macOS 10. As I said, it is now independent from the system mode (dark/light).

**Comment by SebastianRasch** [comment] 2021-04-11 15:47
By the way, the 'classic' icon still works as intended. It is only the new icon in 'Auto' mode, it should be dynamic as well, just like the classic one.

**Comment by JonathonH-PIA** [comment] 2021-04-11 18:26
Ahh, I understand now @SebastianRasch , thank you for clarifying the issue!  Reopening this since it's not a duplicate.

Just to summarize my comment on #5, which should have been posted here since that's actually a different issue, I think we need a grayscale version of the modern icon that we can allow the OS to colorize correctly to solve this.

**Comment by JonathonH-PIA** [comment] 2021-07-19 18:20
@SebastianRasch We've added this in 2.10 (now in silent release on our web site) - the old "auto" option was replaced with a "System" selection that always matches the system icon color.

Internally this uses grayscale versions of the app icons that macOS can colorize, like the classic icons.

Closing this, let me know if there are any further issues with the new icon themes.

**Closed by JonathonH-PIA** 2021-07-19 18:20 UTC

**Comment by SebastianRasch** [comment] 2021-07-28 08:21
Yes works fine, thank you!
